In [1]:
a = 6
b = 5.5
print(type(a))
print(type(a))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

<class 'int'>
<class 'int'>
11.5
0.5
33.0
1.0909090909090908


In [2]:
import numpy as np
print(np.isscalar(2.1))
print(np.isscalar([2.1]))
print(np.isscalar(False))

True
False
True


In [3]:
x = [1,2,3]
y = [4,5,6]
print(type(x))
print(x+y)
z = np.add(x,y)
print(z)
print(type(z))



#mul = np.cross(x,y)
#print(mul)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
<class 'numpy.ndarray'>


In [4]:
a = np.matrix([x,y])
sum = a.sum()
sum

21

In [5]:
mul = 7*a
mul

matrix([[ 7, 14, 21],
        [28, 35, 42]])

In [6]:
sum_mat = 1+a
sum_mat

matrix([[2, 3, 4],
        [5, 6, 7]])

In [7]:
p = np.matrix([[1,2],[4,3]])
q = np.matrix([[3,4],[3,10]])
print(p.shape)
print(q.shape)
m_sum = np.add(p,q)
print(m_sum)
print(m_sum.shape)

(2, 2)
(2, 2)
[[ 4  6]
 [ 7 13]]
(2, 2)


In [9]:
a = [[2,4,4],[3,5,3],[2,2,1]]
b = [[5],[4],[3]]
c = np.matmul(a,b)
c


array([[38],
       [44],
       [21]])

In [12]:
a = [[2,4,4],[3,5,3],[2,2,1]]
z = [[5,5,5],[4,4,4],[3,3,3]]
sol = np.matmul(z,a)
sol

array([[35, 55, 40],
       [28, 44, 32],
       [21, 33, 24]])

In [13]:
print(np.diag(sol))

[35 44 24]


In [15]:
a = [[2,4,4],[3,5,3],[2,2,1]]
z = [[5,5,5],[4,4,4],[3,3,3]]
sol1 = np.matmul(a,z)
print(np.diag(sol1))

[38 44 21]


In [16]:
t = np.transpose(a)
t

array([[2, 3, 2],
       [4, 5, 2],
       [4, 3, 1]])

In [18]:
A = np.array([[6,1,1,3],[4,-2,5,1],[0,0,0,0],[4,3,5,3]])
print(A.shape)
print("Rank of A:",np.linalg.matrix_rank(A))

(4, 4)
Rank of A: 3


In [21]:
A = np.array([[6,1,1],[4,-2,5],[0,0,0],[4,3,5]])
print(A.shape)
print("Rank of A:",np.linalg.matrix_rank(A))

(4, 3)
Rank of A: 3


In [22]:
A = np.array([[6,1,1],[4,-2,5],[4,3,5]])
print(A.shape)
print("Rank of A:",np.linalg.matrix_rank(A))
print("nTrace of A:",np.trace(A))

(3, 3)
Rank of A: 3
nTrace of A: 9


In [24]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Determinant of A:", np.linalg.det(A))


Determinant of A: -306.0


In [25]:
#power of matrix(means multiply matrixs)
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("<atrix A raised to power 3:\n",np.linalg.matrix_power(A,3))

<atrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [27]:
b = np.identity(3)
s = np.matmul(A,b)
s

array([[ 6.,  1.,  1.],
       [ 4., -2.,  5.],
       [ 2.,  8.,  7.]])

In [29]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("INverse of matrix:\n",np.linalg.inv(A))

INverse of matrix:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [30]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
w,v = np.linalg.eig(A)
#eigen values
w

array([11.24862343,  5.09285054, -5.34147398])

In [31]:
#egin vectors
v

array([[ 0.24511338,  0.75669314,  0.02645665],
       [ 0.40622202, -0.03352363, -0.84078293],
       [ 0.88028581, -0.65291014,  0.54072554]])

In [34]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
x = np.linalg.solve(a,b)
x

array([2., 3.])

In [36]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
b = np.array([6,-4,27])
x = np.linalg.solve(a,b)
x

array([ 5.,  3., -2.])