In [0]:
import numpy as np
import tensorflow as tf

In [0]:
hello = tf.constant("Hello World")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
#define tf session
sess = tf.Session()

#run the session
print(sess.run(hello))

b'Hello World'


In [0]:
#Rank 0 tensor
tensor = tf.constant(2)
shape = tf.shape(tensor)
rank = tf.rank(tensor)
print(tensor)

Tensor("Const_1:0", shape=(), dtype=int32)


In [0]:
sess.run(rank)

0

In [0]:
sess.run(shape)

array([], dtype=int32)

In [0]:
tensor = tf.constant([1,2,3])
shape = tf.shape(tensor)
rank = tf.rank(tensor)
print(tensor)
print(sess.run(rank))
sess.run(shape)

Tensor("Const_2:0", shape=(3,), dtype=int32)
1


array([3], dtype=int32)

In [0]:
tensor = tf.constant([[1,2,3],[4,5,6]])
shape = tf.shape(tensor)
rank = tf.rank(tensor)
print(tensor)
print(sess.run(rank))
sess.run(shape)

Tensor("Const_3:0", shape=(2, 3), dtype=int32)
2


array([2, 3], dtype=int32)

In [0]:
tensor = tf.constant([[[1,2,3],[4,5,6]]])
shape = tf.shape(tensor)
rank = tf.rank(tensor)
print(tensor)
print(sess.run(rank))
sess.run(shape)

Tensor("Const_4:0", shape=(1, 2, 3), dtype=int32)
3


array([1, 2, 3], dtype=int32)

In [0]:
a = tf.constant([1.0,2.0],dtype = tf.float32)
b = tf.constant([3.0,4.0])
total = a+b
print(a)
print(b)
print(total)

Tensor("Const_5:0", shape=(2,), dtype=float32)
Tensor("Const_6:0", shape=(2,), dtype=float32)
Tensor("add:0", shape=(2,), dtype=float32)


In [0]:
sess = tf.Session()
sess.run(total)

array([4., 6.], dtype=float32)

In [0]:
with tf.Session():
  x = tf.constant([[2,4],[5,6]])
  y = tf.constant([[1,0],[0,1]])
  z = tf.matmul(x,x) + tf.matmul(x,y)
  #run graph
  result = z.eval() #short for sess.run(z)

In [0]:
result

array([[26, 36],
       [45, 62]], dtype=int32)

In [0]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

z = x+y
# Define session for executing the graph
# Feed_dict argument of the run method to feed concrete values
print(sess.run(z, feed_dict = {x:4, y:5.2}))
print(sess.run(z, feed_dict ={x: [1,2], y:[5,6]}))

9.2
[6. 8.]


In [0]:
pi = tf.constant(3.14, name="pi")
r = tf.placeholder(tf.float32, name="r")

a = pi * r * r

In [0]:
graph = tf.get_default_graph()
print(graph.get_operations())

[<tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation 'Shape' type=Const>, <tf.Operation 'Rank' type=Const>, <tf.Operation 'Const_2' type=Const>, <tf.Operation 'Shape_1' type=Const>, <tf.Operation 'Rank_1' type=Const>, <tf.Operation 'Const_3' type=Const>, <tf.Operation 'Shape_2' type=Const>, <tf.Operation 'Rank_2' type=Const>, <tf.Operation 'Const_4' type=Const>, <tf.Operation 'Shape_3' type=Const>, <tf.Operation 'Rank_3' type=Const>, <tf.Operation 'Const_5' type=Const>, <tf.Operation 'Const_6' type=Const>, <tf.Operation 'add' type=AddV2>, <tf.Operation 'Const_7' type=Const>, <tf.Operation 'Const_8' type=Const>, <tf.Operation 'MatMul' type=MatMul>, <tf.Operation 'MatMul_1' type=MatMul>, <tf.Operation 'add_1' type=AddV2>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'Placeholder_1' type=Placeholder>, <tf.Operation 'add_2' type=AddV2>, <tf.Operation 'pi' type=Const>, <tf.Operation 'r' type=Placeholder>, <tf.Operation 'mul' type=Mul>, <tf.O